name: Fly Deploy
on:
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  MOVIE_DB_API_KEY: ${{ secrets.MOVIE_DB_API_KEY }}
  CLIENT_URL: ${{ vars.CLIENT_URL }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Remove server port property
        run: sed -i 's|server.port.*| |g' src/main/resources/application.properties
      - name: Change moviedb api key
        run: sed -i "s|moviedb.api.key.*|moviedb.api.key=$MOVIE_DB_API_KEY|g" src/main/resources/application.properties
      - name: Change app cross origin url
        run: sed -i 's|cross.origin.url.*|cross.origin.url=$CLIENT_URL|g' src/main/resources/application.properties
      - name: Build project with Maven
        run: mvn -B package --file pom.xml
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
